Configuration files updated
octoposprime/op-be-auth pull request #40
Opened 2024-05-20 13:10 UTC by Smnrgcl

Close #22 
    This pull request updates the configuration settings in the **config/internal.yml** and **config/internal_test.ym**l files to reflectchanges in our service architecture. The updates involve adding new authentication service host and port configurations and removing existing user service settings to streamline our infrastructure setup.

2024-05-20 14:00 UTC, Feyzanrs submitted a review, later dismissed

2024-05-21 12:49 UTC, Sddilora requested changes
I realized that we need to user_host and port to communicate with user service, please add them again

2024-05-21 14:16 UTC, husamettinarabaci requested changes

2024-05-21 14:16 UTC, husamettinarabaci commented on config/internal.yml
> + authentication_host: "op-be-auth"
I think there is an space problem.

2024-06-01 06:35 UTC, Sddilora approved these changes

2024-06-01 08:47 UTC, ebrarkesici approved these changes

2024-06-01 09:15 UTC, Feyzanrs approved these changes

2024-06-03 18:58 UTC, johsquaree approved these changes

2024-06-04 06:19 UTC, husamettinarabaci approved these changes

2024-06-04 06:40 UTC, merged