Updated internal local.yml configuration
octoposprime/op-be-auth pull request #41
Opened 2024-05-20 13:43 UTC by Smnrgcl

Close #23
   This pull request updates the local configuration settings in the **config/internal_local.yml** file to reflect changes in our service architecture. The update includes adding new authentication service configurations.

2024-05-20 14:04 UTC, Feyzanrs submitted a review, later dismissed

2024-05-21 12:38 UTC, Sddilora requested changes
I realized that we need to user_host and port to communicate with user service, please add them again

2024-06-01 06:31 UTC, Sddilora approved these changes

2024-06-01 08:46 UTC, ebrarkesici approved these changes

2024-06-01 09:14 UTC, Feyzanrs approved these changes

2024-06-01 09:14 UTC, merged